#
# tiddlywiki-docker
# cd pipeline to build and publish container
#

name: "CD: Publish tiddlywiki-docker to GHCR"
on:
  push: {}
jobs:
  build-push:
    name: "Build & Push tiddlywiki-docker"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # required to retrieve all tags
          fetch-depth: '0'
      - name: "Get image version"
        id: get-version
        run: |
          IMAGE_VERSION=$(git describe | tr -d "v")
          echo "::set-output name=version::$IMAGE_VERSION"
      - name: "Build tiddlywiki-docker"
        env:
          IMAGE_VERSION: ${{ steps.get-version.version }}
        run: |
          make
      - name: "Authenticate with GHCR"
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: "Publish image to GHCR (latest)"
        env:
          IMAGE_VERSION: ${{ steps.get-version.version }}
        run: make push-latest
      - name: "Publish image to GHCR (version: ${{ steps.get-version.version }})"
        env:
          IMAGE_VERSION: ${{ steps.get-version.version }}
        run: make push
